name: MuleSoft CI/CD POC
on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
          
      - name: Build and Deploy to CloudHub
        env:
          # This pulls the secrets you just created into the script
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
        run: |
          mvn clean deploy -DmuleDeploy \
          -Danypoint.username=$ANYPOINT_USERNAME \
          -Danypoint.password=$ANYPOINT_PASSWORD \
          -DskipTests
